### ISSUE TITLE
New Design for MultiPlay

### ISSUE THREAD

**Issue by ghost** [chaBiselx/multiPlay#1]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a beautiful icon. 

Cheers.

@Yasujizr

*Graphic Designer*

**Comment by chaBiselx** [comment]
HI,

I asked has several friends to tell me an opinion on your works, they find that it is too simple and your images are impersonal (we do not know the main function of the application with the logo).

i'm sorry but  I am not interested.

Cheers 

@chaBiselx

Web Designer
