### ISSUE TITLE
Logo proposal for MULTIPLAY

### ISSUE THREAD

**Issue by ggabogarcia** [chaBiselx/multiPlay#2]
Hello, I'm a graphic designer and I like to collaborate with open source projects. I would like to design a logo for your Project I will be happy to collaborate with you :)

**Comment by chaBiselx** [comment]
hi ! 

I saw your work and I think it's good. can you suggest some sketch to have the choice and to make a decision ?

I already have a logo that I like but I'm not a designer :
https://github.com/chaBiselx/multiPlay/blob/master/src/assets/img/MultiPlay.png

cordially

**Comment by ggabogarcia** [comment]
Hello sir, it would be great, I will make some sketches :+1:

**Comment by ggabogarcia** [comment]
Hello again @chaBiselx  :), this is my proposal, inspired by the logo you [provided](https://github.com/chaBiselx/multiPlay/blob/master/src/assets/img/MultiPlay.png), but correcting details. The design is simple but visually attractive, in the image I show different forms of use, you can use the logo in very dark backgrounds and very clear, it adapts to any environment. Remember that you can make any suggestion you want :)

![multiplay1](https://user-images.githubusercontent.com/35750428/41015799-7eb707b8-6911-11e8-9e5c-a784975c5098.png)

**Comment by chaBiselx** [comment]
I like the second line with the purple and green but the transition color disturb me.
PS: it's a good job

**Comment by ggabogarcia** [comment]
Great thank you. The color can be changed, any suggestions that you would like?

**Comment by chaBiselx** [comment]
Apart from the transition color it's perfect, perhaps add another color between (blue or cyan)

**Comment by ggabogarcia** [comment]
@chaBiselx I will make some samples sir

**Comment by ggabogarcia** [comment]
Check [this](https://i.imgur.com/vvzNd8d.png) sir :)

**Comment by chaBiselx** [comment]
it's good for me you can create a Pull request with the second line
logo in app : https://github.com/chaBiselx/multiPlay/tree/master/src/assets/img
icons on phone: https://github.com/chaBiselx/multiPlay/tree/master/icon

**Comment by ggabogarcia** [comment]
Excellent sir, I will send you the best files to your mail, PNG, SVG, so you can make full use of the logo. :)

**Comment by ggabogarcia** [comment]
@chaBiselx Hello sir, here is the link with the editable files, png and svg. Any other request let me know :)

## [FILES](https://drive.google.com/drive/folders/1ZWR7vwWuSf8QP_uEB75h88uLLsvN1DYL?usp=sharing)

![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by chaBiselx** [comment]
I added your name in my project and in the readme
